name: Sync with upstream

on:
  repository_dispatch:
    types: [sync]

  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout target repository
        uses: actions/checkout@v2
        with:
          repository: AndyADF/toditico-web
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}

      - name: Set up Git user
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'

      - name: Add upstream repository
        run: git remote add upstream https://github.com/Toditico/toditico-web.git

      - name: Fetch upstream changes
        run: git fetch upstream

      - name: Sync upstream changes excluding workflows
        run: |
          git checkout upstream/main -- .
          rsync -av --progress . ../sync_dir --exclude .github/workflows
          rsync -av --progress ../sync_dir/ .
          git add .
          git commit -m "Sync with upstream excluding workflows" || echo "No changes to commit"
          git push origin main --force
