name: Sync with upstream

on:
  repository_dispatch:
    types: [sync]

  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout target repository
        uses: actions/checkout@v2
        with:
          repository: AndyADF/toditico-web
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}

      - name: Add upstream repository
        run: git remote add upstream https://github.com/Toditico/toditico-web.git

      - name: Fetch upstream changes
        run: git fetch upstream

      - name: Merge upstream changes
        run: git merge upstream/main --allow-unrelated-histories

      - name: Push changes
        run: git push origin main
